WebTutRazorViewEngine/Models/PersonViewModel.cs
using System;
using System.Collections.Generic;

namespace WebTutRazorViewEngine.Models
{
    public class PersonViewModel
    {
        public string FirstName {  get; set; }
        public string LastName { get; set; }
        public int Age {  get; set; }
        public Gender Gender { get; set; }
        public List<string> FavoriteMovies { get; set; }
        public bool IsVoter {  get; set; }
        public string Profession { get; set; }
        public AddressViewModel Address { get; set; }
    }

    public class AddressViewModel
    {
        public string Brgy { get; set; }
        public string City { get; set; }
    }

    public enum Gender
    {
        Male,
        Female
    }
}

WebTutRazorViewEngine/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using WebTutRazorViewEngine.Models;

namespace WebTutRazorViewEngine.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            var person = new PersonViewModel()
            {
                FirstName = "Richmond",
                LastName = "Batoto",
                Gender = Gender.Male,
                Age = 21,
                FavoriteMovies = new List<string> { "Pirates of the Caribbean", "Miss Peregrine Home for Peculiar Children" }
            };

            return View(person);
        }

        public IActionResult Create()
        {
            return View(new PersonViewModel());
        }

        public IActionResult Createv2()
        {
            return View(new PersonViewModel()
            {
                FirstName = "Frace",
                IsVoter = true,
                Profession = "Programmer"
            });
        }

        public IActionResult Save(PersonViewModel submittedMode) 
        {
            //Do something here

            return View("Result", submittedMode);
        }

        public IActionResult TestFullName()
        {
            return PartialView("_FullName", new PersonViewModel
            {
                FirstName = "Test",
                LastName = "Only"
            });
        }
    }
}

WebTutRazorViewEngine/ViewComponents/MyMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace WebTutRazorViewEngine.ViewComponents
{
    public class MyMenuViewComponent : ViewComponent
    {
        private IEnumerable<Menu> _menus;

        public MyMenuViewComponent()
        {
            _menus = new List<Menu>()
            {
                new Menu { MenuText = "Create Form v1", ActionName = "Create", ControllerName="Home"},
                new Menu { MenuText = "Create Form v2", ActionName = "CreateV2", ControllerName = "Home"}
            };
        }

        public async Task<IViewComponentResult> InvokeAsync(string brandName)
        {
            ViewData["BrandName"] = brandName;

            return View(_menus);
        }
    }

    public class Menu
    {
        public string MenuText { get; set; }
        public string ActionName { get; set; }
        public string ControllerName {  get; set; }
    }
}

WebTutRazorViewEngine/Views/Home/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model PersonViewModel
@{
    var movies = new[] { "Titanic", "Avatar", "Tarminator" };
}
@* Html helper *@
<div class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3>Information</h3>
                </div>
                <div class="card-body">
                    @using (Html.BeginForm("Save", "Home", FormMethod.Post))
                    {
                        <div class="form-group">
                            @Html.LabelFor(m => m.FirstName)
                            @Html.TextBoxFor(m => m.FirstName, new {@class = "form-control"})
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.LastName)
                            @Html.TextBoxFor(m => m.LastName, new {@class = "form-control"})
                        </div>
                        <div>
                            @Html.LabelFor(m => m.Age)
                            @Html.TextBoxFor(m => m.Age, new {@class = "form-control"})
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.FavoriteMovies)
                            @Html.DropDownListFor(
                                m => m.FavoriteMovies,
                                movies.Select( s => new SelectListItem(s, s)), //the first s is the content that will display in the html, then second s is the value="name" means it is the value when you select that item
                                new {@class = "form-control", multiple = "multiple"}
                            )
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.IsVoter)
                            @Html.CheckBoxFor(m => m.IsVoter)
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.Profession)
                            @Html.RadioButtonFor(m => m.Profession, "Programmer")Programmer
                            @Html.RadioButtonFor(m => m.Profession, "Sea Man")Sea Man
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.Gender)
                            @Html.DropDownListFor(m => m.Gender, Html.GetEnumSelectList<Gender>(), new { @class = "form-control"})
                        </div>
                    }
                </div>
                <div class="card-footer">
                    @Html.ActionLink("Goto Home", "Index", "Home")
                    <button type="submit" class="btn btn-primary">Submit Now!</button>
                </div>
            </div>
        </div>
    </div>
</div>

WebTutRazorViewEngine/Views/Home/CreateV2.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model PersonViewModel
@{
    var movies = new[] { "Titanic", "Avatar", "Terminator" };
}
@* Html tag helper *@
<div class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3>Information</h3>
                </div>
                <div class="card-body">
                    <form asp-action="Save" asp-controller="Home" method="post">
                        <div class="form-group">
                            <label asp-for="FirstName"></label>
                            <input asp-for="FirstName" class="form-control"/>
                        </div>
                        <div class="form-group">
                            <label asp-for="LastName"></label>
                            <input asp-for="LastName" class="form-control" />
                        </div>
                        <div>
                            <label asp-for="Age"></label>
                            <input asp-for="Age" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label asp-for="FavoriteMovies"></label>
                            <select asp-for="FavoriteMovies"
                                    asp-items="movies.Select(s => new SelectListItem(s, s))"
                                    class="form-control" multiple></select>
                        </div>
                        <div class="form-group">
                            <label asp-for="IsVoter"></label>
                            <input asp-for="IsVoter"/>
                        </div>
                        <div class="form-group">
                            <label asp-for="Profession"></label>
                            <div>
                                <input type="radio" asp-for="Profession" value="Programmer"/> I am a Programmer
                                <input type="radio" asp-for="Profession" value="Sea Man" /> I am a Sea Man
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="Gender"></label>
                            <select asp-for="Gender"
                                    asp-items=" Html.GetEnumSelectList<Gender>()"
                                    class="form-control"></select>
                        </div>
                        <hr />
                        <h3>Address</h3>
                        <div class="form-group">
                            <label asp-for="Address.Brgy"></label>
                            <input asp-for="Address.Brgy" class="form-control"/>
                        </div>
                        <div class="form-group">
                            <label asp-for="Address.City"></label>
                            <input asp-for="Address.City" class="form-control" />
                        </div>
                        <div class="card-footer">
                            <a asp-action="Index" asp-controller="Home">Goto Home</a>
                            <button type="submit" class="btn btn-primary">Submit Now!</button>
                        </div>
                    </form>
                </div>
                
            </div>
        </div>
    </div>
</div>

WebTutRazorViewEngine/Views/Home/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    @model PersonViewModel;

    @section CustomStyles{
        <link rel="stylesheet" href="@Url.Content("~/css/home.css")"/>
    }

    @section CustomScripts{
        <script src="@Url.Content("~/js/home.js")"></script>
    }
}
<div class="px-4 pt-5 my-5 text-center border-bottom">
    <h1 class="display-4 fw-bold text-body-emphasis">Centered screenshot</h1>
    <div class="col-lg-6 mx-auto">
        <p class="lead mb-4">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit, featuring Sass variables and mixins, responsive grid system, extensive prebuilt components, and powerful JavaScript plugins.</p>
        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
            <button type="button" class="btn btn-primary btn-lg px-4 me-sm-3">Primary button</button>
            <button type="button" class="btn btn-outline-secondary btn-lg px-4">Secondary</button>
        </div>
    </div>
    <div class="overflow-hidden" style="max-height: 30vh;">
        <div class="container px-5">
            <img src="@Url.Content("~/images/skeleton.png")" class="img-fluid border rounded-3 shadow-lg mb-4" alt="Example image" width="700" height="500" loading="lazy">
        </div>
    </div>
</div>
@{
    var num1 = 3;
    int num2 = 2;
    var result = num1 + num2;
}
@* <span class="text-danger font-weight-bold">Result: @result</span>
<ul>
    @for (var a = 0; a < 5; a++)
    {
        if ( a % 2 == 0)
        {
            <li class="text-primary">@a</li>
        }
        else
        {
            <li class="text-danger">@a</li>
        }
    }
</ul> *@
@Model.FirstName <br />
@Model.LastName <br />
@PrintFullName()<br />
*****HTML Raw*****
<br />
@Html.Raw(PrintFullName())
<br />
*****Partial*****
@Html.PartialAsync("_FullName").Result

*****Partial from variable*****
@{
    var html = await Html.PartialAsync("_FullName");
    @html
}

*****For gender*****
<p>
    @(await Html.PartialAsync("_Kasarian", Model.Gender))
</p>

*****Render Partial*****
@{
    await Html.RenderPartialAsync("_FullName");
}

***** Others *****
<p>
    @if (Model.Gender == Gender.Male)
    {
        //What is your profession?
        <span>What is your profession?</span>
        @:What is your profession?
        <text>
            Aho!! <br />
            Ahot!!
        </text>
    }

  @*   @Model.LastName@yahoo.com
    @(Model.LastName)@yahoo.com *@

    frace@yahoo.com
    @Model.LastName@@yahoo.com
    @(Model.LastName)@@yahoo.com
    <span>@Model.LastName</span><span>@@yahoo.com</span>
</p>

@functions{
    string PrintFullName()
    {
        return $"{Model.FirstName}<br /> {Model.LastName}";
    }
}

WebTutRazorViewEngine/Views/Home/Result.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model PersonViewModel
<div class="content">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="row">
                    <div class="col-12">
                        <partial name="_FullName" />
                    </div>
                    <div class="col-12">
                        <partial name="_Kasarian" model="Model.Gender" />
                    </div>
                    <div class="col-12">
                        <span class="font-weight-bold">Age: </span> @Model.Age
                    </div>
                    <div class="col-12">
                        <span class="font-weight-bold">Profession: </span> @Model.Profession
                    </div>
                    <div>
                        <span class="font-weight-bold">Is Voter? : </span> @(Model.IsVoter ? "Yes" : "No")
                    </div>
                    <div>
                        <span class="font-weight-bold">Fav Movies : </span> @(string.Join(",", Model.FavoriteMovies))
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-6">
    <div class="card">
        <div class="card-header">
            <h3>Address</h3>
        </div>
        <div class="card-body">
            <div class="row">
                <span class="font-weight-bold">Brgy: </span> @Model.Address?.Brgy
            </div>
            <div class="row">
                <span class="font-weight-bold">City: </span> @Model.Address?.City
            </div>
        </div>
    </div>
</div>

WebTutRazorViewEngine/Views/Home/_FullName.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
   @model PersonViewModel

}
<p class="border border-danger">
    @Model.FirstName <br /> @Model.LastName
</p>

WebTutRazorViewEngine/Views/Shared/Components/MyMenu/Default.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<ViewComponents.Menu>
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <a class="navbar-brand" asp-action="Index" asp-controller="Home">@ViewData["BrandName"]</a>
    <div class="collapse navbar-collapse">
        <ul class="navbar-nav">
            @foreach (var menu in Model)
            {
                <li class="nav-item">
                    <a class="nav-link"
                       asp-action="@menu.ActionName"
                       asp-controller="@menu.ControllerName">@menu.MenuText</a>
                </li>
            }
        </ul>
    </div>
</nav>

WebTutRazorViewEngine/Views/Shared/_Kasarian.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Gender
@if (Model == Gender.Male)
{
    <span class="text-success">Lalaki</span>
}
else
{
    <span class="text-danger">Babae</span>
}

WebTutRazorViewEngine/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en" data-bs-theme="dark">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="utf-8"/>
    <title>@ViewBag.Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
    <link rel="stylesheet" href="@Url.Content("~/css/main.css")"/>
    @RenderSection("CustomStyles", false)
</head>
<body>
    <div class="container" id="Home"> 
        @* <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
            <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none"> 
                <svg class="bi me-2" width="40" height="32" aria-hidden="true">
                    <use xlink:href="#bootstrap">
                    </use>
                </svg> 
                <span class="fs-4">Simple header</span> 
            </a>
            <ul class="nav nav-pills"> 
                <jsli class="nav-item">
                    <a href="#" class="nav-link active" aria-current="page">Home</a>
                </jsli> 
                <li class="nav-item">
                    <a href="@Url.Action("TestFullName", "Home")" class="nav-link">Partial</a>
                    </li>
                <li class="nav-item">
                    <a asp-action="Createv2" asp-controller="Home" class="nav-link">Createv2</a>
                    </li>
                <li class="nav-item">
                    <a asp-action="Create" asp-controller="Home" class="nav-link">Create</a>
                    </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">About</a>
                    </li> 
            </ul> 
        </header>  *@
        @* @await Component.InvokeAsync("MyMenu", new {brandName = "My Website - Razor View Engine"})  *@ // html helper
        <vc:my-menu brand-name="My Website - Razor View Engine"></vc:my-menu> // html tag helper
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    <div class="container">
        <footer class="py-3 my-4"> 
            <ul class="nav justify-content-center border-bottom pb-3 mb-3"> 
                <li class="nav-item">
                    @* <a href="#div1">Goto Div1</a> *@
                    <a href="#Home" class="nav-link px-2 text-body-secondary">Home</a>
                </li> 
                <li class="nav-item">
                    <a href="#" class="nav-link px-2 text-body-secondary">Features</a>
                </li> 
                <li class="nav-item">
                    <a href="#" class="nav-link px-2 text-body-secondary">Pricing</a>
                </li> 
                <li class="nav-item">
                    <a href="#" class="nav-link px-2 text-body-secondary">FAQs</a>
                </li> 
                <li class="nav-item">
                    <a href="#" class="nav-link px-2 text-body-secondary">About</a>
                </li> 
            </ul> 
            <p class="text-center text-body-secondary">© 2025 Company, Inc</p> 
        </footer> 
    </div>
    <script src="@Url.Content("~/js/main.js")"></script>
    @RenderSection("CustomScripts", false)
</body>
</html>